title: "Teletubbies"
theme: jekyll-theme-hacker

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S1-CS2103T-W15-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
